options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/nexlink-prod/nexlink-be:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/nexlink-prod/nexlink-be:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting deployment to Cloud Run"
        gcloud run deploy nexlink-be \
          --image gcr.io/nexlink-prod/nexlink-be:latest \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated
        echo "Deployment completed"

images:
  - 'gcr.io/nexlink-prod/nexlink-be:latest'
